[book]
authors = ["Jon Häggblad"]
language = "en"
multilingual = false
src = "src"
title = "Accountable Safety for GRANDPA"

[output.html]
mathjax-support = true

[preprocessor.graphviz]
command = "mdbook-graphviz"

[preprocessor.katex]
